### ISSUE TITLE
Workshop Prerequisites & Reports

### ISSUE THREAD

**Issue by vasmohi** [AElfProject/aelf-dapp-factory#108]
---
name:  📋 Technical Workshop Preparation SOP
about: Create a new ticket for preparing for a technical workshop.
title: aelfinity Developer Workshop with RNS Institute of Technology 
labels: 'documentation'
assignees: vasmohi (Mohit Vashistha)

---

# Technical Workshop Preparation SOP

## Responsibilities
**Workshop Coordinator**: Overall responsibility for planning and execution.
- Mohit Vashistha (vasmohi)

**Support Staff**: Standby to assist on corresponding services on the workshop day itself.
- Zhi Feng Lee - Testnet faucet, Explorer, aelf testnet node
- Loong Yong En -  aelf-playground, aelf-studio
- Ean Zhao, Ghaskata Rutikbhai (maybe) -  For potential issues during workshop

## Content Summary
- [x] Workshop Date : Tuesday, 8th October 2024
- [x] Number of Participants: ~100
- [x] Workshop agenda  

Topics Covered
            -     Smart Contract Fundamentals
            -     Robust Blockchain Security Measures
            -     Real-World Security Incidents
            -     Effective Vulnerability Mitigation Strategies
            -     Best Practices for Secure Development
            -     Introduction to aelf ecosystem
            -     Writing and Deploying Smart Contracts on the aelf blockchain
        
Event Agenda
    -     Morning Session: Smart Contract Security
            -     10:00 AM - 10:15 AM: Registration
            -     10:15 AM - 11:10 AM: Smart Contract Security Fundamentals 
            -     11:10 AM - 11:30 AM: Q&A on Smart Contract Security
            -     11:30 AM - 12:00 PM: Portkey Wallet Setup & Faucet Distribution
            -     12:00 PM - 1:15 PM: Lunch & Networking
    -     Afternoon Session: Hands-on Smart Contract Development
            -     1:15 PM - 1:30 PM: Development Environment Setup 
            -     1:30 PM - 2:30 PM: Smart Contract Implementation 
            -     2:30 PM - 3:00 PM: dApp Frontend Implementation 
            -     3:00 PM - 3:15 PM: Refreshment Break
            -     3:15 PM - 3:45 PM: Submissions and Review
            

- [x] Topics (Paste documentation links below)  
    1. https://aelfblockchain.sg.larksuite.com/wiki/TMAgwivX0i5IowkxXnClbbIagm5
    2. https://docs.aelf.com/quick-start/developers/
    3. https://playground.aelf.com/

### Preparation
- [x] Identify software and tools used
    - [x] `aelf-command`
    - [x] `aelf-deploy`
    - [x] `AElf.ContractTemplates`
- [x] Inform all Support Staff of workshop date

### Pre-Workshop Testing (1 day before workshop)
- [x] Ensure all software and tools stated above are able to be installed.
- [x] Ensure all software and tools stated above are functioning.
- [x] Ensure there are enough tokens in faucet
    - [x] ELF (Mainchain) = 50000
    - [x] ELF (Sidechain) = Not required
    - [x] SEED (Mainchain) = Not required

### Backup Plans
- [x] Prepare contingency plans for technical issues.

### Feedback Collection
- [x] Feedback forms  
1. Attendance Form: https://docs.google.com/forms/d/1Pg-XKue9CE24Ah057Vi2zZvQRu6E3S3xZnfBDlEWpok/viewform?edit_requested=true
2. Tutorial Feedback: https://docs.google.com/forms/d/e/1FAIpQLSed_1CxNimSjetGsccoLd8DyRLjX4594ZvKV9RF4-YiL_y0dQ/viewform?usp=sf_link
3. Event Feedback: https://docs.google.com/forms/d/1UUXApKqFFu_xxXOQbFedbrJx3QyF5Ub0d-tyx-12Lrs/edit
4. aelf Playground Feedback: https://docs.google.com/forms/d/e/1FAIpQLScBE9zoobsxSgfd9F33kkJCwJhBtFXNCNbtmFmwirTEA3i-Lw/viewform?usp=sf_link
5. aelf-Studio Feedback: https://docs.google.com/forms/d/e/1FAIpQLSf4Ot3Q11emYZnL19_QvvXkNxTsGkBhYSmYyZxRYtSzlxb3jw/viewform?usp=sf_link

### Evaluation and Reporting
- [x] Evaluate the success of the workshop based on participant feedback and achievement of objectives.
- [x] Prepare a report summarizing the outcomes and areas for improvement.
- [x] Close this issue.

**Comment by arg-foo** [comment]
@vasmohi For Explorer and aelf testnet node, please inform Jim of the estimated volume

**Comment by arg-foo** [comment]
@vasmohi Can I also know which tutorial will be used for the workshop? Do remember to construct your feedback form according to the tutorial used.
